# Notebook para compara y determinar el mejor modelo

In [1]:
import pandas as pd

In [2]:
# Realizar análisis comparativo completo con los archivos proporcionados

# Cargar los archivos CSV correctamente a los resultados con datos aumentados
yolo8_df = pd.read_csv('../resultados/YOLOv8/300_epochs/results.csv')
yolo10_df = pd.read_csv('../resultados/YOLOv10/300_epochs/results.csv')
yolo11_df = pd.read_csv('../resultados/YOLO11/300_epochs/results.csv')

# Cargar los archivos CSV correctamente a los resultados sin datos aumentados
# yolo8_df = pd.read_csv('../runs/detect/train23/results.csv')
# yolo10_df = pd.read_csv('../runs/detect/train25/results.csv')
# yolo11_df = pd.read_csv('../runs/detect/train24/results.csv')

# Limpiar espacios en nombres de columnas para cada DataFrame
datasets = {'YOLOv8': yolo8_df, 'YOLOv10': yolo10_df, 'YOLOv11': yolo11_df}
results_list = []

# Analizar cada dataset
for name, df in datasets.items():
    df.columns = df.columns.str.strip()
    df = df.copy()
    df['fitness'] = 0.9 * df['metrics/mAP50-95(B)'] + 0.1 * df['metrics/mAP50(B)']
    
    best_epoch_idx = df['fitness'].idxmax()
    best_epoch_number = df.loc[best_epoch_idx, 'epoch']
    best_fitness = df.loc[best_epoch_idx, 'fitness']
    
    precision = df.loc[best_epoch_idx, 'metrics/precision(B)']
    recall = df.loc[best_epoch_idx, 'metrics/recall(B)']
    mAP50 = df.loc[best_epoch_idx, 'metrics/mAP50(B)']
    mAP50_95 = df.loc[best_epoch_idx, 'metrics/mAP50-95(B)']
    
    # Calcular el F1-score
    f1_score = 2 * (precision * recall) / (precision + recall)
    
    results_list.append({
        'Versión': name,
        'Mejor Época': best_epoch_number,
        'Fitness': best_fitness,
        'Precisión': precision,
        'Recall': recall,
        'mAP@0.5': mAP50,
        'mAP@0.5:0.95': mAP50_95,
        'F1-score': f1_score
    })

# Crear DataFrame con resumen de resultados
final_results_df = pd.DataFrame(results_list)

display(final_results_df)

final_results_df.to_csv('best_metrics_yolov8_yolov10_yolo11_con_aumento_datos.csv', index=False)
# final_results_df.to_csv('best_metrics_yolov8_yolov10_yolo11_sin_aumento_datos.csv', index=False)

,Versión,Mejor Época,Fitness,Precisión,Recall,mAP@0.5,mAP@0.5:0.95,F1-score
0,YOLOv8,49,0.739567,0.94455,0.84767,0.93583,0.71776,0.893492
1,YOLOv10,105,0.743859,0.78940,0.94923,0.92943,0.72324,0.861969
2,YOLOv11,102,0.752573,0.89824,0.90425,0.96149,0.72936,0.901235

In [3]:
import pandas as pd 

df = pd.read_csv('best_metrics_yolov8_yolov10_yolo11_con_aumento_datos.csv')
# df = pd.read_csv('best_metrics_yolov8_yolov10_yolo11_sin_aumento_datos.csv')

display(df)

,Versión,Mejor Época,Fitness,Precisión,Recall,mAP@0.5,mAP@0.5:0.95,F1-score
0,YOLOv8,49,0.739567,0.94455,0.84767,0.93583,0.71776,0.893492
1,YOLOv10,105,0.743859,0.78940,0.94923,0.92943,0.72324,0.861969
2,YOLOv11,102,0.752573,0.89824,0.90425,0.96149,0.72936,0.901235